### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Anen** [immortius/gw2-wardrobe-unlock#1]
Just build the app on OSX. File handlers are not closed correctly, leading to ulimit being reached.
Solution: use .close() where required

**Comment by immortius** [comment]
Further information would be good. As far as I'm aware all input streams are closed after use (try with resources is extensively used) - which part of the code triggers this?

**Comment by Anen** [comment]
In ApiCacher and CacheAccessor, there are calls to JsonWriter and BufferedReader but they are never closed. I'll probably create a PR for this issue, got some free time over the next few days.
I am not sure that is THE solution, but that fixed the below errors I was having. I have hundreds of those errors in some build logs.

```
0:05:26.841 [pool-11-thread-1] ERROR au.net.immortius.wardrobe.gw2api.ApiCacher - Failed to write file cache/api/prices/14553.json
java.nio.file.FileSystemException: cache/api/prices/14553.json: Too many open files in system
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:222)
        at java.base/java.nio.file.Files.newBufferedWriter(Files.java:2994)
        at au.net.immortius.wardrobe.gw2api.ApiCacher.retrieveAndSave(ApiCacher.java:186)
        at au.net.immortius.wardrobe.gw2api.ApiCacher.retrieveAndSave(ApiCacher.java:173)
        at au.net.immortius.wardrobe.gw2api.ApiCacher.lambda$cacheIds$0(ApiCacher.java:126)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

```
19:31:38.301 [main] ERROR au.net.immortius.wardrobe.gw2api.CacheAccessor - Failed to load PriceData 26323
java.nio.file.FileSystemException: cache/api/prices/26323.json: Too many open files in system
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:373)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:424)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:158)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2913)
        at java.base/java.nio.file.Files.newBufferedReader(Files.java:2945)
        at au.net.immortius.wardrobe.gw2api.CacheAccessor.get(CacheAccessor.java:72)
        at au.net.immortius.wardrobe.gw2api.PullCurrentPrices.lambda$run$2(PullCurrentPrices.java:97)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
        at au.net.immortius.wardrobe.gw2api.PullCurrentPrices.run(PullCurrentPrices.java:92)
        at au.net.immortius.wardrobe.UpdateSite.main(UpdateSite.java:39)
```

**Comment by immortius** [comment]
I'm investigating.  It looks like I haven't been closing DirectoryStreams, so it might be that - will push some fixes there in the next few days.

**Comment by immortius** [comment]
Try now, let me know if this fixes it.

**Comment by Anen** [comment]
Looks good to me too.
