### ISSUE TITLE
Warning: HK2 failure

### ISSUE THREAD

**Issue by Anen** [immortius/gw2-wardrobe-unlock#5]
Build the app on OSX. I have multiple occurences of the following. No idea where it is coming from, nor if it is related to my machine.

```
Apr 01, 2019 3:43:35 AM org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: HK2 failure has been detected in a code that does not run in an active Jersey Error scope.
WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3143)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2363)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1378)
        at org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1374)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
        at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1374)
        at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1317)
        at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
        at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:148)
        at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:180)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129)
        at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180)
        at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740)
        at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
        at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
        at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:329)
        at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:157)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:265)
        at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
        at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4411)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329)
        at au.net.immortius.wardrobe.gw2api.ApiCacher.availableIds(ApiCacher.java:105)
        at au.net.immortius.wardrobe.gw2api.PullCurrentPrices.run(PullCurrentPrices.java:84)
        at au.net.immortius.wardrobe.UpdateSite.main(UpdateSite.java:39)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 45 more
MultiException stack 2 of 2
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
        implementation=org.glassfish.jersey.message.internal.DataSourceProvider
        contracts={javax.ws.rs.ext.MessageBodyWriter,javax.ws.rs.ext.MessageBodyReader}
        scope=javax.inject.Singleton
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=
        rank=0
        loader=null
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=14
        locatorId=1
        identityHashCode=702999333
        reified=false)
        at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:705)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
        at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
        at org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
        at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
        at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
        at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
        at org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:329)
        at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:157)
        at org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:265)
        at org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
        at org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4411)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:438)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:329)
        at au.net.immortius.wardrobe.gw2api.ApiCacher.availableIds(ApiCacher.java:105)
        at au.net.immortius.wardrobe.gw2api.PullCurrentPrices.run(PullCurrentPrices.java:84)
        at au.net.immortius.wardrobe.UpdateSite.main(UpdateSite.java:39)
```

**Comment by immortius** [comment]
What JDK version are you using? I'm seeing some references to this issue being introduced in JDK 9 - I developed under 8.

**Comment by Anen** [comment]
I am using JDK 12. 

```
$ java -version
openjdk version "12" 2019-03-19
OpenJDK Runtime Environment (build 12+33)
OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**Comment by immortius** [comment]
I was able to reproduce under JDK 11, so it is a new JDK issue. I will have a look into updating to JDK 11 - I'm not interested in having to support non-LTS (Long Term Support) versions of Java like 12 though, so you are on your own with any issues there.

**Comment by immortius** [comment]
Should be fixed now.
